jenkinsci/throttle-concurrent-builds-plugin

pom.xml
src/test/java/hudson/plugins/throttleconcurrents/ThrottleConcurrentTest.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleQueueTaskDispatcherTest.java

I added two test to verify the behaviour of the throttle-concurrent-builds plugin. If these are accepted I will try to add some caching.
If you try these tests against 1.607 they will fail and expose JENKINS-27708.
If you want to have a different core version, then I am fine with that, too. Please tell me which one to use.
If you think there should be additional tests then tell me and I will try to add them.

Acceptance Test for categories

---

src/main/java/hudson/plugins/throttleconcurrents/ThrottleJobProperty.java
src/main/java/hudson/plugins/throttleconcurrents/ThrottleQueueTaskDispatcher.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleJobPropertyTest.java

Hi,
We have a project type, which does not extend AbstractProject, but directly extends Job and implements Queue.Task (we have certain reasons to not extend AbstractProject). We would like to have the Throttle plugin working with it, but it's tied to AbstractProject. 
This pull request unties it from AbstractProject class and makes so, that the Throttle plugin works with any class which extends Job and implements Queue.Task. 
This is just a technical patch, no new features added.

Reduce applicability requirements

---

src/test/java/hudson/plugins/throttleconcurrents/ThrottleIntegrationTest.java
src/test/java/hudson/plugins/throttleconcurrents/testutils/ExecutorWaterMarkRetentionStrategy.java

No tests see `ThrottleJobProperty` actually works when running builds.
I introduced `ExecutorWaterMarkRetentionStrategy` which counts how many builds run on the node at the same time, and added tests to see `ThrottleJobProperty` controls the number of concurrent builds.
This is preparation for the work for [JENKINS-25326](https://issues.jenkins-ci.org/browse/JENKINS-25326), which requires tests to see how `ThrottleJobProperty` works when called from executor thread.

Added tests to verify ThrottleJobProperty actually works for builds

---

src/main/java/hudson/plugins/throttleconcurrents/ThrottleQueueTaskDispatcher.java

This pull request is focused on resolving occurrences of Sonar rule "squid:S00122 -  Statements should be on separate lines" information about the issues here:
https://dev.eclipse.org/sonar/rules/show/squid:S00122
Please let me know if you have any questions.
Sameer Misger

Fixing squid:S00122 -  Statements should be on separate lines

---

pom.xml

In throttle-concurrents-1.8.5 the core version has been bumped to 1.596.1. It was a bad idea, because Jenkins 1.535 ... 1.609.2 are known to be unstable due to the issues in the Queue implementation (on-demand thread spawning for executors).
Effectively there are two Jenkins queue implementations now: the legacy one and 1.609.x+. I want to drop the support of the old implementation in order to cleanup the code and to reduce the support efforts.
@abayer @jglick

Update the core dependency to 1.609.3

---

pom.xml
src/main/java/hudson/plugins/throttleconcurrents/ThrottleQueueTaskDispatcher.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleIntegrationTest.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleQueueTaskDispatcherTest.java

[JENKINS-25326](https://issues.jenkins-ci.org/browse/JENKINS-25326)
Throttling doesn't work for projects in cloudbees-folder with latest Jenkins.
As far as I tested, it doesn't work since Jenkins 1.536:
| Jenlkins | Throttling in folder | Note |
|:---------|:---------------------|:-----|
| 1.532    | Works                | |
| 1.535    | Works                | |
| 1.536    | **Doesn't work**     | |
| 1.554    | **Doesn't work**     | |
| 1.642    | **Doesn't work**     | Requires some changes in test codes to compile |
I fix that problem in followng steps in this request:
1. Add a commit to add a test to reproduce the problem. This requires to change the targeted Jenkins version to >= 1.536.
2. Add a commit to fix the problem.
3. Add a commit to revert changes to reproduce the problem, …

[JENKINS-25326] Elevates to SYSTEM when handling throttling for builds

---

README.md

It is a follow-up to https://issues.jenkins-ci.org/browse/JENKINS-44411, which has been originally reported as bug.
@reviewbybees @abayer

[JENKINS-44411] - Extend documentation to clarify throttle() behavior

---

pom.xml

This broke links like on https://jenkins.io/doc/developer/extensions/jenkins-core/#jobproperty
cc @reviewbybees

POM scm url was wrong.

---

.mvn/extensions.xml
.mvn/maven.config
Jenkinsfile
pom.xml
src/test/java/hudson/plugins/throttleconcurrents/ThrottleIntegrationTest.java
src/test/java/hudson/plugins/throttleconcurrents/testutils/HtmlUnitHelper.java

This is the first of a series of changes to get this plugin's builds and tests into decent shape as described in jenkins-infra/repository-permissions-updater#1325. After this change is merged, I plan to update the `Jenkinsfile` to use `buildPlugin.recommendedConfigurations()`. After that, I plan to clean up and improve the tests. And after that, I plan to merge the fixes for jenkinsci/throttle-concurrent-builds-plugin#57 and jenkinsci/throttle-concurrent-builds-plugin#58.
This PR implements the following:
- Updates the plugin parent POM to [the latest version](https://github.com/jenkinsci/plugin-pom/releases).
- Sets the POM URL to the plugin's GitHub URL, which is the [current recommended best practice](https://github.com/jenkinsci/archetypes/blob/8a49c0c784267d8baf3841199fa4292aad18225a/ …

Update plugin parent POM to latest version

---

Jenkinsfile
pom.xml

I plan to add some new tests to this plugin soon. Before doing so, it would be good to ensure that these tests get run on both the minimum supported version of Jenkins (2.60.3) as well as a more recent LTS version. To that end, I am adding test runs for Jenkins 2.164.1 on Java 8 in addition to the tests we are already running for Jenkins 2.60.3 on Java 8.
While I was here, I updated some dependencies to _slightly_ newer versions. The existing dependencies were from early 2017. I updated these to versions from later in 2017. This makes testing more realistic, as the tests will now be running against a slightly more recent set of plugins, which better aligns with how users are actually running Jenkins. I didn't upgrade any plugins past the 2017 versions in order to minimize risk and …

Add recent LTS line to CI build

---

src/test/java/hudson/plugins/throttleconcurrents/ThrottleIntegrationTest.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleJobPropertyTest.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleQueueTaskDispatcherTest.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleStepTest.java

Now that the plugin POM is up-to-date and the CI system is running tests on both Jenkins 2.60.3 and Jenkins 2.164.1 (a recent LTS release), let's start cleaning up the tests in preparation for some future changes. This will give us a solid baseline to measure future changes against.
This PR makes the following changes to tests:
- Migrate from deprecated `HudsonTestCase` to `JenkinsRule`
- Migrate from deprecated `@Bug` to `@Issue`
- Remove unnecessary `throws` declarations in tests
- Simplify JUnit assertions

Test cleanup

---

src/test/java/hudson/plugins/throttleconcurrents/ThrottleStepTest.java

`ThrottleStep#onePerNodeParallel` has been frequently observed to flake as follows:
```
13:58:54  [ERROR] Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 144.794 s <<< FAILURE! - in hudson.plugins.throttleconcurrents.ThrottleStepTest
13:58:54  [ERROR] onePerNodeParallel(hudson.plugins.throttleconcurrents.ThrottleStepTest)  Time elapsed: 23.362 s  <<< FAILURE!
13:58:54  java.lang.AssertionError:
13:58:54  Started
13:58:54  [Pipeline] parallel
13:58:54  [Pipeline] [a] { (Branch: a)
13:58:54  [Pipeline] [b] { (Branch: b)
13:58:54  [Pipeline] [c] { (Branch: c)
13:58:54  [Pipeline] [a] throttle
13:58:54  [Pipeline] [a] {
13:58:54  [Pipeline] [b] throttle
13:58:54  [Pipeline] [b] {
13:58:54  [Pipeline] [c] throttle
13:58:54  [Pipeline] [c] {
13:58:54  [Pipeline] [a] echo …
```

Fix flakiness in ThrottleStep#onePerNodeParallel

---

src/test/java/hudson/plugins/throttleconcurrents/ThrottleIntegrationTest.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleJobPropertyTest.java

Adds some additional tests in preparation for the merge of jenkinsci/throttle-concurrent-builds-plugin#57:
- We rename `ThrottleIntegrationTest#testThrottlingWithCategory` to `ThrottleIntegrationTest#testThrottlingWithCategoryPerNode` to reflect that it sets `maxConcurrentPerNode`. Then we add a new test: `ThrottleIntegrationTest#testThrottlingWithCategoryTotal`. This is similar to `ThrottleIntegrationTest#testThrottlingWithCategoryPerNode` but sets `maxConcurrentTotal` instead of `maxConcurrentPerNode` for additional code coverage.
- We convert `ThrottleJobPropertyTest` to `RestartableJenkinsRule` and add two new tests: `ThrottleJobPropertyTest#twoTotal` and `ThrottleJobPropertyTest#twoTotalWithRestart`. `ThrottleJobPropertyTest#twoTotal` is similar to`ThrottleStepTest#twoTotal` but uses …

Add more tests

---

src/main/java/hudson/plugins/throttleconcurrents/ThrottleQueueTaskDispatcher.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleIntegrationTest.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleStepTest.java

See [JENKINS-45571](https://issues.jenkins-ci.org/browse/JENKINS-45571) and [JENKINS-53223](https://issues.jenkins-ci.org/browse/JENKINS-53223).
Pipeline sometimes inscrutably leaks flyweight executors. When this happens, it breaks the Throttle Concurrent Builds plugin, which counts flyweight executors when determining how many builds of a job are running. Not only does this result in builds being erroneously throttled, but it also chews up CPU on the Jenkins master in stacks like this:
```
"jenkins.util.Timer [#4]" #77 daemon prio=5 os_prio=0 tid=0x00007f50a800e800 nid=0x80d runnable [0x00007f504788a000]
java.lang.Thread.State: RUNNABLE
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1282)
at …
```

Use FlowExecutionList to calculate the number of running pipeline jobs

---

pom.xml
src/main/java/hudson/plugins/throttleconcurrents/ThrottleJobProperty.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleJobPropertyTest.java

It was impossible to delete all categories (neither at once nor one by
one), since when not receiving any categories, the last-saved categories
took precedence. This has been solved by initializing the categories
property when not receiving the categories from the configuration form.

[JENKINS-54578] Cannot delete last category

---

src/main/java/hudson/plugins/throttleconcurrents/ThrottleJobProperty.java

I pulled inspiration for this change from https://github.com/jenkinsci/branch-api-plugin/pull/127, so I'm hoping it's a fairly straightforward change. In my local testing (using `mvn hpi:run` and then manually installing `Pipeline: Declarative`) I can confirm that before this change, the dropdown suggestions for the Declarative Directive Generator for `options` included only `throttle` and after this change it included both `throttle` and `throttleJobProperty`. When `throttleJobProperty` was selected the UI that came up was as expected for the job property exposed by this plugin.
Also tested by creating a pipeline job and setting this as its pipeline script:
```groovy
pipeline {
agent any
options {
throttleJobProperty(
categories: [],
limitOneJobWithMatchingParams: false, …
```

[JENKINS-60481] Add throttleJobProperty @Symbol to ThrottleJobProperty

---

src/test/java/hudson/plugins/throttleconcurrents/ThrottleCategoryTest.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleConcurrentTest.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleIntegrationTest.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleJobPropertyTest.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleQueueTaskDispatcherTest.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleStepTest.java

More cleanup of tests, this time fixing IntelliJ IDE warnings. I intentionally did not fix warnings in non-test code to minimize risk. The remaining non-test warnings can be fixed at a later time when this plugin is in a better-maintained state.

More test cleanup

---

src/main/java/hudson/plugins/throttleconcurrents/ThrottleQueueTaskDispatcher.java

Introducing a feature flag to allow for the new code path added in #57 to be disabled, just in case it turns out to have unanticipated consequences in production after it is released.

Add feature flag for #57

---

Jenkinsfile

There has recently been some instability around `buildPlugin.recommendedConfigurations()` and even some talk of deprecating it entirely, so let's stop relying on it and define our own testing matrix. I've provided comments explaining the matrix I've chosen. The matrix is similar to that used by `buildPlugin.recommendedConfigurations()`. There are two differences:
- I am using the latest LTS release rather than 2.164.1 to get testing on the bleeding edge of the compatibility spectrum.
- I am adding a recent LTS release Java 8 build on Linux in addition to the recent lts release Java 8 build on Windows. This is to help when debugging Windows failures by providing an apples-to-apples comparison between Windows and non-Windows. Without adding this to the matrix, one would not be able to tell …

Remove usage of deprecated buildPlugin.recommendedConfigurations()

---

src/test/java/hudson/plugins/throttleconcurrents/ThrottleJobPropertyTest.java

See [JENKINS-46858](https://issues.jenkins.io/browse/JENKINS-46858). Cleaned up version of the test from #77 by @jimklimov.

Add test for JENKINS-46858 Comma separated parameters doesn't limit jobs

---

src/main/java/hudson/plugins/throttleconcurrents/ThrottleJobProperty.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleJobPropertyTest.java

See [JENKINS-46858](https://issues.jenkins.io/browse/JENKINS-46858). Cleaned up version of #77 by @jimklimov. Fixes the failing test added in #103.

[JENKINS-46858] Jobs not throttled by comma-separated parameters

---

src/main/java/hudson/plugins/throttleconcurrents/ThrottleQueueTaskDispatcher.java
src/test/java/hudson/plugins/throttleconcurrents/TestUtil.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleJobPropertyFreestyleTest.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleJobPropertyPipelineTest.java

Adds test coverage for this functionality for both classic job types and Pipeline jobs. The test for classic job types passed without the changes to `src/main`, but the test for Pipeline jobs failed without the changes to `src/main` due to [JENKINS-37809](https://issues.jenkins.io/browse/JENKINS-37809). With the changes to `src/main`, the test for Pipeline jobs now passes.

[JENKINS-37809] Throttling based on parameters does not work with Pipeline jobs

---

src/main/resources/hudson/plugins/throttleconcurrents/ThrottleJobProperty/config.jelly

Fixes checkboxes layout for categories selection on job options.
On current versions of jenkins, the first category checkbox is being rendered to the left of the section title causing confusion to the user.
I was able to fix it changing the separate label element to title attribute in checkbox.
I am not a frontend developer, so I don't know if this is the better solution. Please review.
Jira ticket: https://issues.jenkins.io/browse/JENKINS-65745
Tested on:
- jenkins: 2.277.4 (official docker image jenkins/jenkins:lts@sha256:3a441b1bcd2ce630b7bad3486e7972a8d107f25098a4a7c28b7f1a96d61742a6)
- throttle-concurrents: 2.2 
Current plugin version:
after selecting cat1 and cat3
After patch:

fixes checkboxes layout for categories selection on job options

---

README.adoc

Infrastructure as Code is essential nowadays and using [Jenkins Configuration as Code](https://plugins.jenkins.io/configuration-as-code/) (aka JCasC) is common in the Kubernetes ecosystem.
This PR to add to the docs an example about how to configure the plugin via JCasC.The Throttle Concurrent Builds plugin is supported out of the box in JCasC ... so this PR just updates the docs.

[Docs] Add an example to configure the plugin via JCasC

---

src/test/java/hudson/plugins/throttleconcurrents/ThrottleJobPropertyTest.java
src/test/java/hudson/plugins/throttleconcurrents/ThrottleQueueTaskDispatcherTest.java

See https://github.com/jenkinsci/jenkins/pull/5842#issuecomment-969521220

Adjustments for form rework

---

README.adoc
pom.xml
src/test/java/hudson/plugins/throttleconcurrents/ThrottleStepTest.java

It is possible to use the throttle step in the options block of a
stage to throttle single stages in a declarative pipeline. This
commit documents this behaviour and adds a test for it.

Add documentation and tests for throttle step in options block

---

src/main/java/hudson/plugins/throttleconcurrents/ThrottleQueueTaskDispatcher.java

This PR fixes problem when option "Prevent multiple jobs with identical parameters from running concurrently" is not working (at least one issue is open: [JENKINS-67978](https://issues.jenkins.io/browse/JENKINS-67978)), and I've seen some similar question on the Internet.
I tested this change manually in my environment. Before applying this patch, parameters were ignored, same job with equal parameters was triggered, didn't wait for the previous job with the same parameter to finish.
After applying the patch, job with the same paparameters is waiting for an existing job with the same parameters to finish - exactly as it shoud..
I am not a programmer, so I'm not able to implement automated tests. I was able to add some debugging and to guess what may fix the problem, but this is already …

[JENKINS-67978] Fix for job parameters on built-in node

---

src/test/java/hudson/plugins/throttleconcurrents/ThrottleQueueTaskDispatcherTest.java

Fixes the test for https://github.com/jenkinsci/jenkins/pull/10913

Fix 'groovyClassPath' test ahead of refined reorderable list
